# Generated by Django 5.1.14 on 2026-09-05 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bushlands", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeedSighting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_reference", models.CharField(blank=True, max_length=500)),
                ("model_id", models.CharField(max_length=100)),
                ("model_top_id", models.CharField(blank=True, max_length=100)),
                ("candidates", models.JSONField(default=list)),
                ("top_scientific_name", models.CharField(blank=True, max_length=255)),
                ("top_common_name", models.CharField(blank=True, max_length=255)),
                ("top_confidence", models.FloatField(blank=True, null=True)),
                ("weedscan_profile", models.JSONField(blank=True, default=dict)),
                ("wikipedia_url", models.URLField(blank=True, max_length=500)),
                ("confirmed_species", models.CharField(blank=True, max_length=255)),
                ("observed_on", models.DateField(blank=True, null=True)),
                (
                    "abundance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single plant"),
                            ("patch", "Small patch"),
                            ("widespread", "Widespread"),
                        ],
                        max_length=20,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, max_length=500)),
                ("identified_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bushland_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weed_sightings",
                        to="bushlands.bushlandarea",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weed_sightings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "weed_sighting",
                "ordering": ["-identified_at"],
                "indexes": [
                    models.Index(
                        fields=["bushland_area", "-identified_at"],
                        name="weed_sighti_bushlan_f69f5c_idx",
                    ),
                    models.Index(
                        fields=["reported_by", "-identified_at"],
                        name="weed_sighti_reporte_a3829d_idx",
                    ),
                    models.Index(
                        fields=["confirmed_species"],
                        name="weed_sighti_confirm_8fb035_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("top_confidence__isnull", True),
                            models.Q(
                                ("top_confidence__gte", 0), ("top_confidence__lte", 1)
                            ),
                            _connector="OR",
                        ),
                        name="weed_sighting_confidence_in_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("latitude__isnull", True),
                            models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                            _connector="OR",
                        ),
                        name="weed_sighting_latitude_in_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("longitude__isnull", True),
                            models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                            _connector="OR",
                        ),
                        name="weed_sighting_longitude_in_range",
                    ),
                ],
            },
        ),
    ]
